def permutations(iterable, r=None):
    """
    From https://github.com/python/cpython/blob/master/Modules/itertoolsmodule.c
    """
    pool = tuple(iterable)
    n = len(pool)
    r = n if r is None else r
    indices = list(range(n))
    cycles = list(range(n - r + 1, n + 1))[::-1]
    yield tuple(pool[i] for i in indices[:r])
    while n:
        for i in reversed(list(range(r))):
            cycles[i] -= 1
            if cycles[i] == 0:
                indices[i:] = indices[i + 1 :] + indices[i : i + 1]
                cycles[i] = n - i
            else:
                j = cycles[i]
                indices[i], indices[-j] = indices[-j], indices[i]
                yield tuple(pool[i] for i in indices[:r])
                break
        else:
            return


odd_cube_center_color_permutations = (
    ("Wh", "OR", "Gr", "Rd", "Bu", "Ye"),
    ("Wh", "Gr", "Rd", "Bu", "OR", "Ye"),
    ("Wh", "Bu", "OR", "Gr", "Rd", "Ye"),
    ("Wh", "Rd", "Bu", "OR", "Gr", "Ye"),
    ("Ye", "Bu", "Rd", "Gr", "OR", "Wh"),
    ("Ye", "Gr", "OR", "Bu", "Rd", "Wh"),
    ("Ye", "Rd", "Gr", "OR", "Bu", "Wh"),
    ("Ye", "OR", "Bu", "Rd", "Gr", "Wh"),
    ("OR", "Ye", "Gr", "Wh", "Bu", "Rd"),
    ("OR", "Wh", "Bu", "Ye", "Gr", "Rd"),
    ("OR", "Gr", "Wh", "Bu", "Ye", "Rd"),
    ("OR", "Bu", "Ye", "Gr", "Wh", "Rd"),
    ("Gr", "Ye", "Rd", "Wh", "OR", "Bu"),
    ("Gr", "Wh", "OR", "Ye", "Rd", "Bu"),
    ("Gr", "Rd", "Wh", "OR", "Ye", "Bu"),
    ("Gr", "OR", "Ye", "Rd", "Wh", "Bu"),
    ("Rd", "Ye", "Bu", "Wh", "Gr", "OR"),
    ("Rd", "Wh", "Gr", "Ye", "Bu", "OR"),
    ("Rd", "Bu", "Wh", "Gr", "Ye", "OR"),
    ("Rd", "Gr", "Ye", "Bu", "Wh", "OR"),
    ("Bu", "Wh", "Rd", "Ye", "OR", "Gr"),
    ("Bu", "Ye", "OR", "Wh", "Rd", "Gr"),
    ("Bu", "Rd", "Ye", "OR", "Wh", "Gr"),
    ("Bu", "OR", "Wh", "Rd", "Ye", "Gr"),
)

# we use a string here (that we split up later) instead of a huge list of tuples to save memory
even_cube_center_color_permutations = """Bu Gr OR Rd Wh Ye
Bu Gr OR Rd Ye Wh
Bu Gr OR Wh Rd Ye
Bu Gr OR Wh Ye Rd
Bu Gr OR Ye Rd Wh
Bu Gr OR Ye Wh Rd
Bu Gr Rd OR Wh Ye
Bu Gr Rd OR Ye Wh
Bu Gr Rd Wh OR Ye
Bu Gr Rd Wh Ye OR
Bu Gr Rd Ye OR Wh
Bu Gr Rd Ye Wh OR
Bu Gr Wh OR Rd Ye
Bu Gr Wh OR Ye Rd
Bu Gr Wh Rd OR Ye
Bu Gr Wh Rd Ye OR
Bu Gr Wh Ye OR Rd
Bu Gr Wh Ye Rd OR
Bu Gr Ye OR Rd Wh
Bu Gr Ye OR Wh Rd
Bu Gr Ye Rd OR Wh
Bu Gr Ye Rd Wh OR
Bu Gr Ye Wh OR Rd
Bu Gr Ye Wh Rd OR
Bu OR Gr Rd Wh Ye
Bu OR Gr Rd Ye Wh
Bu OR Gr Wh Rd Ye
Bu OR Gr Wh Ye Rd
Bu OR Gr Ye Rd Wh
Bu OR Gr Ye Wh Rd
Bu OR Rd Gr Wh Ye
Bu OR Rd Gr Ye Wh
Bu OR Rd Wh Gr Ye
Bu OR Rd Wh Ye Gr
Bu OR Rd Ye Gr Wh
Bu OR Rd Ye Wh Gr
Bu OR Wh Gr Rd Ye
Bu OR Wh Gr Ye Rd
Bu OR Wh Rd Gr Ye
Bu OR Wh Rd Ye Gr
Bu OR Wh Ye Gr Rd
Bu OR Wh Ye Rd Gr
Bu OR Ye Gr Rd Wh
Bu OR Ye Gr Wh Rd
Bu OR Ye Rd Gr Wh
Bu OR Ye Rd Wh Gr
Bu OR Ye Wh Gr Rd
Bu OR Ye Wh Rd Gr
Bu Rd Gr OR Wh Ye
Bu Rd Gr OR Ye Wh
Bu Rd Gr Wh OR Ye
Bu Rd Gr Wh Ye OR
Bu Rd Gr Ye OR Wh
Bu Rd Gr Ye Wh OR
Bu Rd OR Gr Wh Ye
Bu Rd OR Gr Ye Wh
Bu Rd OR Wh Gr Ye
Bu Rd OR Wh Ye Gr
Bu Rd OR Ye Gr Wh
Bu Rd OR Ye Wh Gr
Bu Rd Wh Gr OR Ye
Bu Rd Wh Gr Ye OR
Bu Rd Wh OR Gr Ye
Bu Rd Wh OR Ye Gr
Bu Rd Wh Ye Gr OR
Bu Rd Wh Ye OR Gr
Bu Rd Ye Gr OR Wh
Bu Rd Ye Gr Wh OR
Bu Rd Ye OR Gr Wh
Bu Rd Ye OR Wh Gr
Bu Rd Ye Wh Gr OR
Bu Rd Ye Wh OR Gr
Bu Wh Gr OR Rd Ye
Bu Wh Gr OR Ye Rd
Bu Wh Gr Rd OR Ye
Bu Wh Gr Rd Ye OR
Bu Wh Gr Ye OR Rd
Bu Wh Gr Ye Rd OR
Bu Wh OR Gr Rd Ye
Bu Wh OR Gr Ye Rd
Bu Wh OR Rd Gr Ye
Bu Wh OR Rd Ye Gr
Bu Wh OR Ye Gr Rd
Bu Wh OR Ye Rd Gr
Bu Wh Rd Gr OR Ye
Bu Wh Rd Gr Ye OR
Bu Wh Rd OR Gr Ye
Bu Wh Rd OR Ye Gr
Bu Wh Rd Ye Gr OR
Bu Wh Rd Ye OR Gr
Bu Wh Ye Gr OR Rd
Bu Wh Ye Gr Rd OR
Bu Wh Ye OR Gr Rd
Bu Wh Ye OR Rd Gr
Bu Wh Ye Rd Gr OR
Bu Wh Ye Rd OR Gr
Bu Ye Gr OR Rd Wh
Bu Ye Gr OR Wh Rd
Bu Ye Gr Rd OR Wh
Bu Ye Gr Rd Wh OR
Bu Ye Gr Wh OR Rd
Bu Ye Gr Wh Rd OR
Bu Ye OR Gr Rd Wh
Bu Ye OR Gr Wh Rd
Bu Ye OR Rd Gr Wh
Bu Ye OR Rd Wh Gr
Bu Ye OR Wh Gr Rd
Bu Ye OR Wh Rd Gr
Bu Ye Rd Gr OR Wh
Bu Ye Rd Gr Wh OR
Bu Ye Rd OR Gr Wh
Bu Ye Rd OR Wh Gr
Bu Ye Rd Wh Gr OR
Bu Ye Rd Wh OR Gr
Bu Ye Wh Gr OR Rd
Bu Ye Wh Gr Rd OR
Bu Ye Wh OR Gr Rd
Bu Ye Wh OR Rd Gr
Bu Ye Wh Rd Gr OR
Bu Ye Wh Rd OR Gr
Gr Bu OR Rd Wh Ye
Gr Bu OR Rd Ye Wh
Gr Bu OR Wh Rd Ye
Gr Bu OR Wh Ye Rd
Gr Bu OR Ye Rd Wh
Gr Bu OR Ye Wh Rd
Gr Bu Rd OR Wh Ye
Gr Bu Rd OR Ye Wh
Gr Bu Rd Wh OR Ye
Gr Bu Rd Wh Ye OR
Gr Bu Rd Ye OR Wh
Gr Bu Rd Ye Wh OR
Gr Bu Wh OR Rd Ye
Gr Bu Wh OR Ye Rd
Gr Bu Wh Rd OR Ye
Gr Bu Wh Rd Ye OR
Gr Bu Wh Ye OR Rd
Gr Bu Wh Ye Rd OR
Gr Bu Ye OR Rd Wh
Gr Bu Ye OR Wh Rd
Gr Bu Ye Rd OR Wh
Gr Bu Ye Rd Wh OR
Gr Bu Ye Wh OR Rd
Gr Bu Ye Wh Rd OR
Gr OR Bu Rd Wh Ye
Gr OR Bu Rd Ye Wh
Gr OR Bu Wh Rd Ye
Gr OR Bu Wh Ye Rd
Gr OR Bu Ye Rd Wh
Gr OR Bu Ye Wh Rd
Gr OR Rd Bu Wh Ye
Gr OR Rd Bu Ye Wh
Gr OR Rd Wh Bu Ye
Gr OR Rd Wh Ye Bu
Gr OR Rd Ye Bu Wh
Gr OR Rd Ye Wh Bu
Gr OR Wh Bu Rd Ye
Gr OR Wh Bu Ye Rd
Gr OR Wh Rd Bu Ye
Gr OR Wh Rd Ye Bu
Gr OR Wh Ye Bu Rd
Gr OR Wh Ye Rd Bu
Gr OR Ye Bu Rd Wh
Gr OR Ye Bu Wh Rd
Gr OR Ye Rd Bu Wh
Gr OR Ye Rd Wh Bu
Gr OR Ye Wh Bu Rd
Gr OR Ye Wh Rd Bu
Gr Rd Bu OR Wh Ye
Gr Rd Bu OR Ye Wh
Gr Rd Bu Wh OR Ye
Gr Rd Bu Wh Ye OR
Gr Rd Bu Ye OR Wh
Gr Rd Bu Ye Wh OR
Gr Rd OR Bu Wh Ye
Gr Rd OR Bu Ye Wh
Gr Rd OR Wh Bu Ye
Gr Rd OR Wh Ye Bu
Gr Rd OR Ye Bu Wh
Gr Rd OR Ye Wh Bu
Gr Rd Wh Bu OR Ye
Gr Rd Wh Bu Ye OR
Gr Rd Wh OR Bu Ye
Gr Rd Wh OR Ye Bu
Gr Rd Wh Ye Bu OR
Gr Rd Wh Ye OR Bu
Gr Rd Ye Bu OR Wh
Gr Rd Ye Bu Wh OR
Gr Rd Ye OR Bu Wh
Gr Rd Ye OR Wh Bu
Gr Rd Ye Wh Bu OR
Gr Rd Ye Wh OR Bu
Gr Wh Bu OR Rd Ye
Gr Wh Bu OR Ye Rd
Gr Wh Bu Rd OR Ye
Gr Wh Bu Rd Ye OR
Gr Wh Bu Ye OR Rd
Gr Wh Bu Ye Rd OR
Gr Wh OR Bu Rd Ye
Gr Wh OR Bu Ye Rd
Gr Wh OR Rd Bu Ye
Gr Wh OR Rd Ye Bu
Gr Wh OR Ye Bu Rd
Gr Wh OR Ye Rd Bu
Gr Wh Rd Bu OR Ye
Gr Wh Rd Bu Ye OR
Gr Wh Rd OR Bu Ye
Gr Wh Rd OR Ye Bu
Gr Wh Rd Ye Bu OR
Gr Wh Rd Ye OR Bu
Gr Wh Ye Bu OR Rd
Gr Wh Ye Bu Rd OR
Gr Wh Ye OR Bu Rd
Gr Wh Ye OR Rd Bu
Gr Wh Ye Rd Bu OR
Gr Wh Ye Rd OR Bu
Gr Ye Bu OR Rd Wh
Gr Ye Bu OR Wh Rd
Gr Ye Bu Rd OR Wh
Gr Ye Bu Rd Wh OR
Gr Ye Bu Wh OR Rd
Gr Ye Bu Wh Rd OR
Gr Ye OR Bu Rd Wh
Gr Ye OR Bu Wh Rd
Gr Ye OR Rd Bu Wh
Gr Ye OR Rd Wh Bu
Gr Ye OR Wh Bu Rd
Gr Ye OR Wh Rd Bu
Gr Ye Rd Bu OR Wh
Gr Ye Rd Bu Wh OR
Gr Ye Rd OR Bu Wh
Gr Ye Rd OR Wh Bu
Gr Ye Rd Wh Bu OR
Gr Ye Rd Wh OR Bu
Gr Ye Wh Bu OR Rd
Gr Ye Wh Bu Rd OR
Gr Ye Wh OR Bu Rd
Gr Ye Wh OR Rd Bu
Gr Ye Wh Rd Bu OR
Gr Ye Wh Rd OR Bu
OR Bu Gr Rd Wh Ye
OR Bu Gr Rd Ye Wh
OR Bu Gr Wh Rd Ye
OR Bu Gr Wh Ye Rd
OR Bu Gr Ye Rd Wh
OR Bu Gr Ye Wh Rd
OR Bu Rd Gr Wh Ye
OR Bu Rd Gr Ye Wh
OR Bu Rd Wh Gr Ye
OR Bu Rd Wh Ye Gr
OR Bu Rd Ye Gr Wh
OR Bu Rd Ye Wh Gr
OR Bu Wh Gr Rd Ye
OR Bu Wh Gr Ye Rd
OR Bu Wh Rd Gr Ye
OR Bu Wh Rd Ye Gr
OR Bu Wh Ye Gr Rd
OR Bu Wh Ye Rd Gr
OR Bu Ye Gr Rd Wh
OR Bu Ye Gr Wh Rd
OR Bu Ye Rd Gr Wh
OR Bu Ye Rd Wh Gr
OR Bu Ye Wh Gr Rd
OR Bu Ye Wh Rd Gr
OR Gr Bu Rd Wh Ye
OR Gr Bu Rd Ye Wh
OR Gr Bu Wh Rd Ye
OR Gr Bu Wh Ye Rd
OR Gr Bu Ye Rd Wh
OR Gr Bu Ye Wh Rd
OR Gr Rd Bu Wh Ye
OR Gr Rd Bu Ye Wh
OR Gr Rd Wh Bu Ye
OR Gr Rd Wh Ye Bu
OR Gr Rd Ye Bu Wh
OR Gr Rd Ye Wh Bu
OR Gr Wh Bu Rd Ye
OR Gr Wh Bu Ye Rd
OR Gr Wh Rd Bu Ye
OR Gr Wh Rd Ye Bu
OR Gr Wh Ye Bu Rd
OR Gr Wh Ye Rd Bu
OR Gr Ye Bu Rd Wh
OR Gr Ye Bu Wh Rd
OR Gr Ye Rd Bu Wh
OR Gr Ye Rd Wh Bu
OR Gr Ye Wh Bu Rd
OR Gr Ye Wh Rd Bu
OR Rd Bu Gr Wh Ye
OR Rd Bu Gr Ye Wh
OR Rd Bu Wh Gr Ye
OR Rd Bu Wh Ye Gr
OR Rd Bu Ye Gr Wh
OR Rd Bu Ye Wh Gr
OR Rd Gr Bu Wh Ye
OR Rd Gr Bu Ye Wh
OR Rd Gr Wh Bu Ye
OR Rd Gr Wh Ye Bu
OR Rd Gr Ye Bu Wh
OR Rd Gr Ye Wh Bu
OR Rd Wh Bu Gr Ye
OR Rd Wh Bu Ye Gr
OR Rd Wh Gr Bu Ye
OR Rd Wh Gr Ye Bu
OR Rd Wh Ye Bu Gr
OR Rd Wh Ye Gr Bu
OR Rd Ye Bu Gr Wh
OR Rd Ye Bu Wh Gr
OR Rd Ye Gr Bu Wh
OR Rd Ye Gr Wh Bu
OR Rd Ye Wh Bu Gr
OR Rd Ye Wh Gr Bu
OR Wh Bu Gr Rd Ye
OR Wh Bu Gr Ye Rd
OR Wh Bu Rd Gr Ye
OR Wh Bu Rd Ye Gr
OR Wh Bu Ye Gr Rd
OR Wh Bu Ye Rd Gr
OR Wh Gr Bu Rd Ye
OR Wh Gr Bu Ye Rd
OR Wh Gr Rd Bu Ye
OR Wh Gr Rd Ye Bu
OR Wh Gr Ye Bu Rd
OR Wh Gr Ye Rd Bu
OR Wh Rd Bu Gr Ye
OR Wh Rd Bu Ye Gr
OR Wh Rd Gr Bu Ye
OR Wh Rd Gr Ye Bu
OR Wh Rd Ye Bu Gr
OR Wh Rd Ye Gr Bu
OR Wh Ye Bu Gr Rd
OR Wh Ye Bu Rd Gr
OR Wh Ye Gr Bu Rd
OR Wh Ye Gr Rd Bu
OR Wh Ye Rd Bu Gr
OR Wh Ye Rd Gr Bu
OR Ye Bu Gr Rd Wh
OR Ye Bu Gr Wh Rd
OR Ye Bu Rd Gr Wh
OR Ye Bu Rd Wh Gr
OR Ye Bu Wh Gr Rd
OR Ye Bu Wh Rd Gr
OR Ye Gr Bu Rd Wh
OR Ye Gr Bu Wh Rd
OR Ye Gr Rd Bu Wh
OR Ye Gr Rd Wh Bu
OR Ye Gr Wh Bu Rd
OR Ye Gr Wh Rd Bu
OR Ye Rd Bu Gr Wh
OR Ye Rd Bu Wh Gr
OR Ye Rd Gr Bu Wh
OR Ye Rd Gr Wh Bu
OR Ye Rd Wh Bu Gr
OR Ye Rd Wh Gr Bu
OR Ye Wh Bu Gr Rd
OR Ye Wh Bu Rd Gr
OR Ye Wh Gr Bu Rd
OR Ye Wh Gr Rd Bu
OR Ye Wh Rd Bu Gr
OR Ye Wh Rd Gr Bu
Rd Bu Gr OR Wh Ye
Rd Bu Gr OR Ye Wh
Rd Bu Gr Wh OR Ye
Rd Bu Gr Wh Ye OR
Rd Bu Gr Ye OR Wh
Rd Bu Gr Ye Wh OR
Rd Bu OR Gr Wh Ye
Rd Bu OR Gr Ye Wh
Rd Bu OR Wh Gr Ye
Rd Bu OR Wh Ye Gr
Rd Bu OR Ye Gr Wh
Rd Bu OR Ye Wh Gr
Rd Bu Wh Gr OR Ye
Rd Bu Wh Gr Ye OR
Rd Bu Wh OR Gr Ye
Rd Bu Wh OR Ye Gr
Rd Bu Wh Ye Gr OR
Rd Bu Wh Ye OR Gr
Rd Bu Ye Gr OR Wh
Rd Bu Ye Gr Wh OR
Rd Bu Ye OR Gr Wh
Rd Bu Ye OR Wh Gr
Rd Bu Ye Wh Gr OR
Rd Bu Ye Wh OR Gr
Rd Gr Bu OR Wh Ye
Rd Gr Bu OR Ye Wh
Rd Gr Bu Wh OR Ye
Rd Gr Bu Wh Ye OR
Rd Gr Bu Ye OR Wh
Rd Gr Bu Ye Wh OR
Rd Gr OR Bu Wh Ye
Rd Gr OR Bu Ye Wh
Rd Gr OR Wh Bu Ye
Rd Gr OR Wh Ye Bu
Rd Gr OR Ye Bu Wh
Rd Gr OR Ye Wh Bu
Rd Gr Wh Bu OR Ye
Rd Gr Wh Bu Ye OR
Rd Gr Wh OR Bu Ye
Rd Gr Wh OR Ye Bu
Rd Gr Wh Ye Bu OR
Rd Gr Wh Ye OR Bu
Rd Gr Ye Bu OR Wh
Rd Gr Ye Bu Wh OR
Rd Gr Ye OR Bu Wh
Rd Gr Ye OR Wh Bu
Rd Gr Ye Wh Bu OR
Rd Gr Ye Wh OR Bu
Rd OR Bu Gr Wh Ye
Rd OR Bu Gr Ye Wh
Rd OR Bu Wh Gr Ye
Rd OR Bu Wh Ye Gr
Rd OR Bu Ye Gr Wh
Rd OR Bu Ye Wh Gr
Rd OR Gr Bu Wh Ye
Rd OR Gr Bu Ye Wh
Rd OR Gr Wh Bu Ye
Rd OR Gr Wh Ye Bu
Rd OR Gr Ye Bu Wh
Rd OR Gr Ye Wh Bu
Rd OR Wh Bu Gr Ye
Rd OR Wh Bu Ye Gr
Rd OR Wh Gr Bu Ye
Rd OR Wh Gr Ye Bu
Rd OR Wh Ye Bu Gr
Rd OR Wh Ye Gr Bu
Rd OR Ye Bu Gr Wh
Rd OR Ye Bu Wh Gr
Rd OR Ye Gr Bu Wh
Rd OR Ye Gr Wh Bu
Rd OR Ye Wh Bu Gr
Rd OR Ye Wh Gr Bu
Rd Wh Bu Gr OR Ye
Rd Wh Bu Gr Ye OR
Rd Wh Bu OR Gr Ye
Rd Wh Bu OR Ye Gr
Rd Wh Bu Ye Gr OR
Rd Wh Bu Ye OR Gr
Rd Wh Gr Bu OR Ye
Rd Wh Gr Bu Ye OR
Rd Wh Gr OR Bu Ye
Rd Wh Gr OR Ye Bu
Rd Wh Gr Ye Bu OR
Rd Wh Gr Ye OR Bu
Rd Wh OR Bu Gr Ye
Rd Wh OR Bu Ye Gr
Rd Wh OR Gr Bu Ye
Rd Wh OR Gr Ye Bu
Rd Wh OR Ye Bu Gr
Rd Wh OR Ye Gr Bu
Rd Wh Ye Bu Gr OR
Rd Wh Ye Bu OR Gr
Rd Wh Ye Gr Bu OR
Rd Wh Ye Gr OR Bu
Rd Wh Ye OR Bu Gr
Rd Wh Ye OR Gr Bu
Rd Ye Bu Gr OR Wh
Rd Ye Bu Gr Wh OR
Rd Ye Bu OR Gr Wh
Rd Ye Bu OR Wh Gr
Rd Ye Bu Wh Gr OR
Rd Ye Bu Wh OR Gr
Rd Ye Gr Bu OR Wh
Rd Ye Gr Bu Wh OR
Rd Ye Gr OR Bu Wh
Rd Ye Gr OR Wh Bu
Rd Ye Gr Wh Bu OR
Rd Ye Gr Wh OR Bu
Rd Ye OR Bu Gr Wh
Rd Ye OR Bu Wh Gr
Rd Ye OR Gr Bu Wh
Rd Ye OR Gr Wh Bu
Rd Ye OR Wh Bu Gr
Rd Ye OR Wh Gr Bu
Rd Ye Wh Bu Gr OR
Rd Ye Wh Bu OR Gr
Rd Ye Wh Gr Bu OR
Rd Ye Wh Gr OR Bu
Rd Ye Wh OR Bu Gr
Rd Ye Wh OR Gr Bu
Wh Bu Gr OR Rd Ye
Wh Bu Gr OR Ye Rd
Wh Bu Gr Rd OR Ye
Wh Bu Gr Rd Ye OR
Wh Bu Gr Ye OR Rd
Wh Bu Gr Ye Rd OR
Wh Bu OR Gr Rd Ye
Wh Bu OR Gr Ye Rd
Wh Bu OR Rd Gr Ye
Wh Bu OR Rd Ye Gr
Wh Bu OR Ye Gr Rd
Wh Bu OR Ye Rd Gr
Wh Bu Rd Gr OR Ye
Wh Bu Rd Gr Ye OR
Wh Bu Rd OR Gr Ye
Wh Bu Rd OR Ye Gr
Wh Bu Rd Ye Gr OR
Wh Bu Rd Ye OR Gr
Wh Bu Ye Gr OR Rd
Wh Bu Ye Gr Rd OR
Wh Bu Ye OR Gr Rd
Wh Bu Ye OR Rd Gr
Wh Bu Ye Rd Gr OR
Wh Bu Ye Rd OR Gr
Wh Gr Bu OR Rd Ye
Wh Gr Bu OR Ye Rd
Wh Gr Bu Rd OR Ye
Wh Gr Bu Rd Ye OR
Wh Gr Bu Ye OR Rd
Wh Gr Bu Ye Rd OR
Wh Gr OR Bu Rd Ye
Wh Gr OR Bu Ye Rd
Wh Gr OR Rd Bu Ye
Wh Gr OR Rd Ye Bu
Wh Gr OR Ye Bu Rd
Wh Gr OR Ye Rd Bu
Wh Gr Rd Bu OR Ye
Wh Gr Rd Bu Ye OR
Wh Gr Rd OR Bu Ye
Wh Gr Rd OR Ye Bu
Wh Gr Rd Ye Bu OR
Wh Gr Rd Ye OR Bu
Wh Gr Ye Bu OR Rd
Wh Gr Ye Bu Rd OR
Wh Gr Ye OR Bu Rd
Wh Gr Ye OR Rd Bu
Wh Gr Ye Rd Bu OR
Wh Gr Ye Rd OR Bu
Wh OR Bu Gr Rd Ye
Wh OR Bu Gr Ye Rd
Wh OR Bu Rd Gr Ye
Wh OR Bu Rd Ye Gr
Wh OR Bu Ye Gr Rd
Wh OR Bu Ye Rd Gr
Wh OR Gr Bu Rd Ye
Wh OR Gr Bu Ye Rd
Wh OR Gr Rd Bu Ye
Wh OR Gr Rd Ye Bu
Wh OR Gr Ye Bu Rd
Wh OR Gr Ye Rd Bu
Wh OR Rd Bu Gr Ye
Wh OR Rd Bu Ye Gr
Wh OR Rd Gr Bu Ye
Wh OR Rd Gr Ye Bu
Wh OR Rd Ye Bu Gr
Wh OR Rd Ye Gr Bu
Wh OR Ye Bu Gr Rd
Wh OR Ye Bu Rd Gr
Wh OR Ye Gr Bu Rd
Wh OR Ye Gr Rd Bu
Wh OR Ye Rd Bu Gr
Wh OR Ye Rd Gr Bu
Wh Rd Bu Gr OR Ye
Wh Rd Bu Gr Ye OR
Wh Rd Bu OR Gr Ye
Wh Rd Bu OR Ye Gr
Wh Rd Bu Ye Gr OR
Wh Rd Bu Ye OR Gr
Wh Rd Gr Bu OR Ye
Wh Rd Gr Bu Ye OR
Wh Rd Gr OR Bu Ye
Wh Rd Gr OR Ye Bu
Wh Rd Gr Ye Bu OR
Wh Rd Gr Ye OR Bu
Wh Rd OR Bu Gr Ye
Wh Rd OR Bu Ye Gr
Wh Rd OR Gr Bu Ye
Wh Rd OR Gr Ye Bu
Wh Rd OR Ye Bu Gr
Wh Rd OR Ye Gr Bu
Wh Rd Ye Bu Gr OR
Wh Rd Ye Bu OR Gr
Wh Rd Ye Gr Bu OR
Wh Rd Ye Gr OR Bu
Wh Rd Ye OR Bu Gr
Wh Rd Ye OR Gr Bu
Wh Ye Bu Gr OR Rd
Wh Ye Bu Gr Rd OR
Wh Ye Bu OR Gr Rd
Wh Ye Bu OR Rd Gr
Wh Ye Bu Rd Gr OR
Wh Ye Bu Rd OR Gr
Wh Ye Gr Bu OR Rd
Wh Ye Gr Bu Rd OR
Wh Ye Gr OR Bu Rd
Wh Ye Gr OR Rd Bu
Wh Ye Gr Rd Bu OR
Wh Ye Gr Rd OR Bu
Wh Ye OR Bu Gr Rd
Wh Ye OR Bu Rd Gr
Wh Ye OR Gr Bu Rd
Wh Ye OR Gr Rd Bu
Wh Ye OR Rd Bu Gr
Wh Ye OR Rd Gr Bu
Wh Ye Rd Bu Gr OR
Wh Ye Rd Bu OR Gr
Wh Ye Rd Gr Bu OR
Wh Ye Rd Gr OR Bu
Wh Ye Rd OR Bu Gr
Wh Ye Rd OR Gr Bu
Ye Bu Gr OR Rd Wh
Ye Bu Gr OR Wh Rd
Ye Bu Gr Rd OR Wh
Ye Bu Gr Rd Wh OR
Ye Bu Gr Wh OR Rd
Ye Bu Gr Wh Rd OR
Ye Bu OR Gr Rd Wh
Ye Bu OR Gr Wh Rd
Ye Bu OR Rd Gr Wh
Ye Bu OR Rd Wh Gr
Ye Bu OR Wh Gr Rd
Ye Bu OR Wh Rd Gr
Ye Bu Rd Gr OR Wh
Ye Bu Rd Gr Wh OR
Ye Bu Rd OR Gr Wh
Ye Bu Rd OR Wh Gr
Ye Bu Rd Wh Gr OR
Ye Bu Rd Wh OR Gr
Ye Bu Wh Gr OR Rd
Ye Bu Wh Gr Rd OR
Ye Bu Wh OR Gr Rd
Ye Bu Wh OR Rd Gr
Ye Bu Wh Rd Gr OR
Ye Bu Wh Rd OR Gr
Ye Gr Bu OR Rd Wh
Ye Gr Bu OR Wh Rd
Ye Gr Bu Rd OR Wh
Ye Gr Bu Rd Wh OR
Ye Gr Bu Wh OR Rd
Ye Gr Bu Wh Rd OR
Ye Gr OR Bu Rd Wh
Ye Gr OR Bu Wh Rd
Ye Gr OR Rd Bu Wh
Ye Gr OR Rd Wh Bu
Ye Gr OR Wh Bu Rd
Ye Gr OR Wh Rd Bu
Ye Gr Rd Bu OR Wh
Ye Gr Rd Bu Wh OR
Ye Gr Rd OR Bu Wh
Ye Gr Rd OR Wh Bu
Ye Gr Rd Wh Bu OR
Ye Gr Rd Wh OR Bu
Ye Gr Wh Bu OR Rd
Ye Gr Wh Bu Rd OR
Ye Gr Wh OR Bu Rd
Ye Gr Wh OR Rd Bu
Ye Gr Wh Rd Bu OR
Ye Gr Wh Rd OR Bu
Ye OR Bu Gr Rd Wh
Ye OR Bu Gr Wh Rd
Ye OR Bu Rd Gr Wh
Ye OR Bu Rd Wh Gr
Ye OR Bu Wh Gr Rd
Ye OR Bu Wh Rd Gr
Ye OR Gr Bu Rd Wh
Ye OR Gr Bu Wh Rd
Ye OR Gr Rd Bu Wh
Ye OR Gr Rd Wh Bu
Ye OR Gr Wh Bu Rd
Ye OR Gr Wh Rd Bu
Ye OR Rd Bu Gr Wh
Ye OR Rd Bu Wh Gr
Ye OR Rd Gr Bu Wh
Ye OR Rd Gr Wh Bu
Ye OR Rd Wh Bu Gr
Ye OR Rd Wh Gr Bu
Ye OR Wh Bu Gr Rd
Ye OR Wh Bu Rd Gr
Ye OR Wh Gr Bu Rd
Ye OR Wh Gr Rd Bu
Ye OR Wh Rd Bu Gr
Ye OR Wh Rd Gr Bu
Ye Rd Bu Gr OR Wh
Ye Rd Bu Gr Wh OR
Ye Rd Bu OR Gr Wh
Ye Rd Bu OR Wh Gr
Ye Rd Bu Wh Gr OR
Ye Rd Bu Wh OR Gr
Ye Rd Gr Bu OR Wh
Ye Rd Gr Bu Wh OR
Ye Rd Gr OR Bu Wh
Ye Rd Gr OR Wh Bu
Ye Rd Gr Wh Bu OR
Ye Rd Gr Wh OR Bu
Ye Rd OR Bu Gr Wh
Ye Rd OR Bu Wh Gr
Ye Rd OR Gr Bu Wh
Ye Rd OR Gr Wh Bu
Ye Rd OR Wh Bu Gr
Ye Rd OR Wh Gr Bu
Ye Rd Wh Bu Gr OR
Ye Rd Wh Bu OR Gr
Ye Rd Wh Gr Bu OR
Ye Rd Wh Gr OR Bu
Ye Rd Wh OR Bu Gr
Ye Rd Wh OR Gr Bu
Ye Wh Bu Gr OR Rd
Ye Wh Bu Gr Rd OR
Ye Wh Bu OR Gr Rd
Ye Wh Bu OR Rd Gr
Ye Wh Bu Rd Gr OR
Ye Wh Bu Rd OR Gr
Ye Wh Gr Bu OR Rd
Ye Wh Gr Bu Rd OR
Ye Wh Gr OR Bu Rd
Ye Wh Gr OR Rd Bu
Ye Wh Gr Rd Bu OR
Ye Wh Gr Rd OR Bu
Ye Wh OR Bu Gr Rd
Ye Wh OR Bu Rd Gr
Ye Wh OR Gr Bu Rd
Ye Wh OR Gr Rd Bu
Ye Wh OR Rd Bu Gr
Ye Wh OR Rd Gr Bu
Ye Wh Rd Bu Gr OR
Ye Wh Rd Bu OR Gr
Ye Wh Rd Gr Bu OR
Ye Wh Rd Gr OR Bu
Ye Wh Rd OR Bu Gr
Ye Wh Rd OR Gr Bu"""
len_even_cube_center_color_permutations = 720
