repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args: ["--config=pyproject.toml", "--check"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.8"
    hooks:
    - id: flake8
      args: ["--config=.flake8"]
-   repo: https://github.com/pycqa/isort
    rev: 5.6.1
    hooks:
    - id: isort
